<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>e455d20f-0caf-4208-9748-858cfcbd6fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;lower&quot;]/div/div[2]/div[2]/div/div[1]/div/div/ol/li/ol/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>registration-fees__pricing-sub-event-block-register-button btn custom-tertiary-color custom-tertiary-text-color</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/events/2018/12356/the-event-director-classic-2020/register?event=56721</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>_ga.track('Register', 'Click', 'Event-pricing-table', 1); </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Register
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lower&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;event-content col-md-14 col-sm-16 col-sm-pull-8-custom middle-section&quot;]/div[@class=&quot;registration-fees&quot;]/div[@class=&quot;registration-fees__wrap&quot;]/div[@class=&quot;registration-fees__pricing-container&quot;]/div[@class=&quot;registration-fees__pricing-body&quot;]/div[@class=&quot;registration-fees__pricing-sub-event&quot;]/ol[@class=&quot;registration-fees__pricing-sub-event-blocks list-unstyled&quot;]/li[@class=&quot;registration-fees__pricing-sub-event-block registration-fees__pricing-sub-event-block--current custom-tertiary-border-color&quot;]/ol[@class=&quot;legacy-pricing-table list-unstyled&quot;]/li[@class=&quot;legacy-pricing-table__row legacy-pricing-table__row--current&quot;]/a[@class=&quot;registration-fees__pricing-sub-event-block-register-button btn custom-tertiary-color custom-tertiary-text-color&quot;]</value>
   </webElementProperties>
</WebElementEntity>
